### ISSUE TITLE
Email address as user ID - option

### ISSUE THREAD

**Issue by zachskaggs** [SproutApps/segment-io#1]
Would it be possible to add an option to the EDD Customer.io/Segment plugin to pass the email address as the user ID instead of a random number?

To give you an idea what we’re doing, we’re pumping our freemius data into customer.io as well so we can’t use a random number for the user ID. we need to know the user ID on the freemius and EDD sides, and setting it to the email address seems the best way to do this to make sure all the customer data stays with the same user records.  Does that make sense?

**Comment by dancameron** [comment]
I'm actually using Freemius too and came up with a solution already. Checkout the freemius add-on - 
https://github.com/SproutApps/segment-io/blob/master/controllers/add-ons/Freemius_Webhook.php

It's not configurable yet (i.e. options) but maybe constants will be the only thing necessary.

What it does though is creates a webhook for Freemius to use, then the data is sent to customer.io (or segment) for the install and uninstall actions. More can definitely be added.

This was the best way I came up with. Do you have another method to get your data into customer.io? Anything additional you need to send?

FYI: the user_id is an encrypted email address, the reason for this is because that id is passed around from via unencrypted callbacks (non-https://).

**Comment by zachskaggs** [comment]
For our use case, Freemius is sending too much traffic to put on the main site where we also handle sales/licensing (400,000+ active installs).  We need the Freemius hooks to be handled elsewhere, but since we still want all the information in the same customer record the user ID in Customer.io has to be predictable instead of random.  The suggestion from the Customer.io team for our use case (sending data from multiple sources) was to set the user ID to the email address.  Figured we'd get your input on it.  The solution you have would totally work if it weren't for the ridiculous amount of traffic we're getting right now from the Freemius integration.

**Comment by dancameron** [comment]
`EDD_Segment_Identity::encrypt` and `EDD_Segment_Identity::decrypt` handle this, so if it weren't for you needing to move to another server for these freemius callbacks you could simply modify those methods. However, I think your best option would be to just encrypt them still, rebuilding the same methods on your new server script.

**Comment by zachskaggs** [comment]
I agree, that should work fine for our needs, thank you so much for the insight!
